# Generated by Django 4.0.6 on 2022-07-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_name', models.CharField(default='', max_length=36)),
                ('last_name', models.CharField(default='', max_length=36)),
                ('doctor', models.CharField(default='', max_length=36)),
                ('photo_type', models.CharField(default='', max_length=36)),
                ('deal_number', models.IntegerField(default=0, max_length=36)),
                ('price_type', models.IntegerField(default=0, max_length=36)),
                ('credit', models.IntegerField(default=0, max_length=36)),
                ('cash', models.IntegerField(default=0, max_length=36)),
                ('reimbursement_from_insurance', models.IntegerField(default=0, max_length=36)),
                ('reference_number', models.IntegerField(default=0, max_length=36)),
                ('invoicing_number', models.IntegerField(default=0, max_length=36)),
                ('way', models.CharField(default='', max_length=36)),
                ('photographer_name', models.CharField(default='', max_length=36)),
            ],
        ),
    ]
