# Generated by Django 4.0.6 on 2022-08-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dental_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.CharField(default='', max_length=36),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.IntegerField(default=0, max_length=36),
        ),
        migrations.AlterField(
            model_name='patient',
            name='price_type',
            field=models.CharField(default=0, max_length=36),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reference_number',
            field=models.CharField(default=0, max_length=36),
        ),
    ]
